librarius/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'books'

urlpatterns = [
    path('', views.HelloPage.as_view(), name='hello'),
    path('book_list', views.IndexView.as_view(), name='index'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('login/', LoginView.as_view(template_name='librarius/user_login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('book/<int:pk>/assign/', views.assign_tome_book, name='assign'),
    path('author/<int:pk>/', views.AuthorPage.as_view(), name='author_page'),
    path('book/<int:pk>/delete/', views.delete_book_entry, name='delete_book'),
    path('book/<int:pk>/update/', views.BookUpdateView.as_view(), name='update_book'),
    path('author/<int:pk>/support', views.author_support, name='support'),
    path('author/<int:pk>/unsupport', views.author_support_decline, name='decline_support'),
    path('create/category/', views.CreateCategoryOfBookView.as_view(), name='category_create'),
    path('create/author/', views.CreateAuthorView.as_view(), name='category_create'),

]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('librarius.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),  # Добавьте эту строку
    ] + urlpatterns

librarius/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


class Book(models.Model):
    holders = models.ManyToManyField(User, default=None, blank=True)
    title = models.CharField(max_length=255)
    author = models.ManyToManyField('Author')
    description = models.TextField()
    publication_date = models.DateField()
    cover_image = models.ImageField(upload_to='covers/', null=True, blank=True)
    category = models.ManyToManyField('Category', related_name='books')
    is_available = models.BooleanField(default=True)
    copy_count = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.title}'
    

class Category(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title
    

class Author(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True, default='')
    avatar_image = models.ImageField(upload_to='author_avatars/', null=True, blank=True)
    supporters = models.ManyToManyField(User, related_name='author_supporters')

    def __str__(self):
        return self.name
    

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    books_assignes = models.ManyToManyField(Book, related_name='user_books')

    def __str__(self):
        return self.user.username
    

class BookReview(models.Model):
    RATES = ((1, 'Bad!'),
             (2, 'Not good'),
             (3, 'Ok'),
             (4, 'Well done!'),
             (5, 'Incredible!'))
    
    book = models.ForeignKey(Book, on_delete=models.CASCADE) 
    rate = models.PositiveIntegerField(choices=RATES, verbose_name="Rating", help_text="Rate the book from 1 to 5.")
    comment = models.TextField(blank=True, null=True)

    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        # Создаем профиль для нового пользователя
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    # Сохраняем профиль при изменении пользователя
    instance.userprofile.save()
    

librarius/forms.py
from django import forms
from .models import Book

from django import forms
from .models import Book, Category, Author

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'holders',
            'title',
            'author',
            'description',
            'publication_date',
            'cover_image',
            'category',
            'is_available',
            'copy_count',
        ]
        widgets = {
            'holders': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the book title'}),
            'author': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'placeholder': 'Enter a brief description'}),
            'publication_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'cover_image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'category': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'is_available': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'copy_count': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={
                'class': 'resize-y h-20 w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500',
                'placeholder': 'Enter the description here...',
                'rows': 1,
            }),
        }
        exclude = ['supporters']


    

    

librarius/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.views.generic import ListView, DetailView, UpdateView, CreateView, TemplateView
from extra_views import ModelFormSetView
from django.urls import reverse, reverse_lazy
from .models import Book, Author, Category, BookReview
from django.views.generic.detail import SingleObjectMixin
from .forms import BookForm, CategoryForm, AuthorForm
from django.contrib.auth.mixins import PermissionRequiredMixin

class IndexView(ListView):
    template_name = 'librarius/index_page.html'
    model = Book
    context_object_name = 'books'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = BookForm()

        return context
    
    def post(self, request, *args, **kwargs):
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()  # сохраняем форму
            return redirect('books:index')  # перенаправляем на главную страницу после успешной отправки формы
        context = self.get_context_data()
        context['form'] = form  # передаем форму с ошибками в контекст, если она невалидна
        return self.render_to_response(context)
    
    
class BookDetailView(DetailView):
    template_name = 'librarius/book_detail.html'
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book_id = self.object.id
        reviews = BookReview.objects.filter(book=book_id)
        context['reviews'] = reviews
        return context
        
def assign_tome_book(request, pk):
    
    book = Book.objects.get(id=pk)
    book.holders.add(request.user)
    book.copy_count -= 1
    book.save()
    

    return redirect('books:index')


class AuthorPage(DetailView):
    model = Author
    template_name = 'librarius/author_page.html'
    context_object_name = 'author'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['obj'] = self.object
        context['supporters_count'] = self.object.supporters.all().count()
        return context


def delete_book_entry(request, pk):
    object = Book.objects.get(pk=pk)
    object.delete()
    return redirect(request.META.get('HTTP_REFERER', '/'))


class BookUpdateView(UpdateView):
    model = Book
    form_class = BookForm
    template_name = 'librarius/book_update.html'
    success_url = reverse_lazy('books:index')


def author_support(request, pk):
    author = Author.objects.get(pk=pk)
    author.supporters.add(request.user)
    return redirect('books:author_page', pk=pk)

def author_support_decline(request, pk):
    author = Author.objects.get(pk=pk)
    author.supporters.delete(request.user)
    author.save()


class CreateCategoryOfBookView(PermissionRequiredMixin, CreateView):
    model = Category
    template_name = 'librarius/create_category.html'
    form_class = CategoryForm
    permission_required = 'is_staff'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return redirect(reverse_lazy('books:index'))
        else:
            return super().dispatch(request, *args, **kwargs)
        

class CreateAuthorView(PermissionRequiredMixin, CreateView):
    model = Author
    template_name = 'librarius/create_author.html'
    form_class = AuthorForm
    permission_required = 'is_staff'
    success_url = reverse_lazy('books:index')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return redirect(reverse_lazy('books:index'))
        else:
            return super().dispatch(request, *args, **kwargs)
        

class HelloPage(TemplateView):
    template_name = 'librarius/hello_page.html'
    

librarius/templates/librarius/author_page.html
{% extends "librarius/base.html" %}
{% block content %}
<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
      <div class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">{{author.name}}
        </h1>
        <p class="mb-8 leading-relaxed">Count of the author supporters: {{supporters_count}}</p>
        <div class="flex justify-center">
          <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Donate to author</button>
          {% if request.user not in obj.supporters.all %}
        <a href='{% url "books:support" author.pk %}'><button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Support the Author</button></a>
          {% endif %}
        </div>
      </div>
      <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
        {% if author.avatar_image %}
        <img class="object-cover object-center rounded" alt="Hero" src='{{ author.avatar_image.url }}'>
        {% else %}
        <img class="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
        {% endif %}  
    </div>
    </div>
  </section>
{% endblock content %}

librarius/templates/librarius/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

        {% block ininal %}{% endblock ininal %}
    </head>
    <body class="bg-gray-100 text-gray-900 tracking-wider leading-normal">
        <header class="text-gray-600 body-font shadow-md bg-white sticky top-0 z-50">
            <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
              <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
                  <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
                </svg>
                <span class="ml-3 text-xl font-bold">Library System {% if user.is_authenticated %}: {{ request.user.username }}{% endif %}</span>
              </a>
              <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center space-x-4">
                <a href="#" class="text-gray-600 hover:text-indigo-500">Home</a>
                <a href="#" class="text-gray-600 hover:text-indigo-500">Books</a>
                <a href="#" class="text-gray-600 hover:text-indigo-500">About</a>
              </nav>
              <div class="mt-4 md:mt-0">
                {% if not user.is_authenticated %}
                <form method='post' action='{% url "books:login" %}' class="inline-block">
                  {% csrf_token %}
                  <button class="inline-flex items-center bg-indigo-500 text-white border-0 py-2 px-4 focus:outline-none hover:bg-indigo-600 rounded text-base">Log in
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                      <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                  </button>
                </form>
                {% else %}
                <form method='post' action='{% url "books:logout" %}' class="inline-block">
                  {% csrf_token %}
                  <button class="inline-flex items-center bg-gray-100 border-0 py-2 px-4 focus:outline-none hover:bg-gray-200 rounded text-base">Log out
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                      <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                  </button>
                </form>
                {% endif %}
              </div>
            </div>
          </header>
    {% block content %}
    {% endblock content %}
</body>
</html>

librarius/templates/librarius/book_detail.html
{% extends "librarius/base.html" %}

{% block content %}
{% load filters %}
<div class="hero bg-base-200 min-h-screen py-10">
  <div class="container mx-auto px-4">
    <div class="hero-content flex-col lg:flex-row lg:gap-10 shadow-lg p-6 rounded-lg bg-white">
      
      <!-- Картинка обложки книги -->
      <div class="w-full lg:w-1/3">
        {% if not book.cover_image %}
          <img
            src="https://img.daisyui.com/images/stock/photo-1635805737707-575885ab0820.webp"
            alt="Default Book Cover"
            class="max-w-full rounded-lg shadow-md"
          />
        {% else %}
          <img
            src="{{ book.cover_image.url }}"
            alt="{{ book.title }}"
            class="max-w-full rounded-lg shadow-md"
          />
        {% endif %}
      </div>

      <!-- Описание книги -->
      <div class="w-full lg:w-2/3">
        <h1 class="text-5xl font-bold text-primary mb-4">{{ book.title }}</h1>

        <p class="py-4 text-gray-700 leading-relaxed">
          {{ book.description }}
        </p>

        <!-- Авторы -->
        <div class="py-4">
          <h3 class="text-lg font-semibold text-secondary mb-2">Author(s):</h3>
          <ul class="list-disc pl-6 text-gray-600">
            {% for authr in book.author.all %}
              <li>{{ authr }}</li>
            {% endfor %}
          </ul>
        </div>

        <!-- Кнопка действия -->
        <div class="py-4">
          {% if request.user not in book.holders.all %}
            <a
              href="{% url 'books:assign' book.pk %}"
              class="inline-block px-6 py-2 text-black bg-primary hover:bg-primary-focus rounded-lg shadow-lg font-semibold transition"
            >
              Hold this Book
            </a>
          {% else %}
            <p class="text-green-600 font-semibold">You already hold this book</p>
          {% endif %}
        </div>
      </div>
      
    </div>

    <!-- Отзывы о книге -->
    <div class="mt-10">
      <h2 class="text-3xl font-bold text-primary mb-6">Reviews</h2>
      {% if reviews %}
        <div class="space-y-6">
          {% for review in reviews %}
            <div class="bg-gray-100 p-6 rounded-lg shadow-md">
              <div class="flex justify-between items-center mb-4">
                <div class="font-semibold text-lg">{{ review.user.username }}</div>
                <div class="text-yellow-500">
                  {% for i in review.rate|to %}
                    ★
                  {% endfor %}
                </div>
              </div>
              <p class="text-gray-700"></p>
            </div>
          {% endfor %}
        </div>
      {% else %}
        <p class="text-gray-600">No reviews yet. Be the first to write a review!</p>
      {% endif %}
    </div>
    
  </div>
</div>

{% endblock content %}

librarius/templates/librarius/book_update.html
{% extends "librarius/base.html" %}
{% block ininal %}
{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
{% endblock ininal %}



{% block content %}
<form method='post'>
    {% csrf_token %}
    {{ form|crispy }}
    <button type='submit'>Submit</button>
</form>
{% endblock content %}

librarius/templates/librarius/create_author.html
{% extends "librarius/base.html" %}

{% load crispy_forms_filters %}

{% block content %}
<style>
    textarea {
        resize: vertical; /* Позволяет менять размер только по вертикали */
        max-height: 300px; /* Максимальная высота */
        min-height: 50px; /* Минимальная высота */
    }
</style>

<div class="min-h-screen flex items-center justify-center bg-gray-50 py-6 sm:py-12">
    <div class="w-full max-w-lg bg-white rounded-lg shadow-lg p-8">
        <h1 class="text-3xl font-bold text-indigo-600 text-center mb-6">Create the new Author</h1>
        <form method="post" enctype="multipart/form-data" class="space-y-6">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full bg-indigo-600 text-white py-2 px-4 rounded-lg shadow-md text-lg hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500">
                Submit
            </button>
        </form>
    </div>
</div>

{% endblock content %}

librarius/templates/librarius/create_category.html
{% extends "librarius/base.html" %}

{% load crispy_forms_filters %}

{% block content %}
<form method='post' align='center'>
    {% csrf_token %}
 {{ form|crispy }}
 <button type='submit' class='bg-gray-300 hover:indigo-300'>Submit</button>
</form>
{% endblock content %}

librarius/templates/librarius/hello_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello Page</title>
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gradient-to-r from-blue-400 to-purple-500 min-h-screen flex items-center justify-center text-white">
    <div class="text-center">
        <h1 class="text-5xl font-bold mb-4">Welcome to the Library System!</h1>
        <p class="text-lg mb-8">Discover a world of knowledge and manage your favorite books effortlessly.</p>
        {% if user.is_authenticated %}
        <div class="flex justify-center">
            <a href="{% url "books:index" %}" class="bg-white text-blue-500 hover:text-blue-700 py-2 px-6 rounded shadow-md font-semibold">Explore Books</a>
        </div>
        {% else %}
        <div class="space-x-4">
            <a href="{% url "books:index" %}" class="bg-white text-blue-500 hover:text-blue-700 py-2 px-6 rounded shadow-md font-semibold">Explore Books</a>
            <a href="{% url "books:login" %}" class="bg-white text-purple-500 hover:text-purple-700 py-2 px-6 rounded shadow-md font-semibold">Log In</a>
        </div>
        {% endif %}
    </div>
</body>
</html>

librarius/templates/librarius/index_page.html
{% extends "librarius/base.html" %}
{% load crispy_forms_tags %}
{% block ininal %}

	<link href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
	<!--Replace with your tailwind.css once created-->
	<!--Regular Datatables CSS-->
	<link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
	<!--Responsive Extension Datatables CSS-->
	<link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

	<style>
		/*Overrides for Tailwind CSS */

		/*Form fields*/
		.dataTables_wrapper select,
		.dataTables_wrapper .dataTables_filter input {
			color: #4a5568;
			padding-left: 1rem;
			padding-right: 1rem;
			padding-top: .5rem;
			padding-bottom: .5rem;
			line-height: 1.25;
			border-width: 2px;
			border-radius: .25rem;
			border-color: #edf2f7;
			background-color: #edf2f7;
		}

		/*Row Hover*/
		table.dataTable.hover tbody tr:hover,
		table.dataTable.display tbody tr:hover {
			background-color: #ebf4ff;
		}

		/*Pagination Buttons*/
		.dataTables_wrapper .dataTables_paginate .paginate_button {
			font-weight: 700;
			border-radius: .25rem;
			border: 1px solid transparent;
		}

		/*Pagination Buttons - Current selected */
		.dataTables_wrapper .dataTables_paginate .paginate_button.current {
			color: #fff !important;
			box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06);
			font-weight: 700;
			background: #667eea !important;
			border: 1px solid transparent;
		}

		/*Pagination Buttons - Hover */
		.dataTables_wrapper .dataTables_paginate .paginate_button:hover {
			color: #fff !important;
			box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06);
			font-weight: 700;
			background: #667eea !important;
			border: 1px solid transparent;
		}

		/*Add padding to bottom border */
		table.dataTable.no-footer {
			border-bottom: 1px solid #e2e8f0;
			margin-top: 0.75em;
			margin-bottom: 0.75em;
		}

		/*Change colour of responsive icon*/
		table.dataTable.dtr-inline.collapsed>tbody>tr>td:first-child:before,
		table.dataTable.dtr-inline.collapsed>tbody>tr>th:first-child:before {
			background-color: #667eea !important;
		}
	</style>
{% endblock ininal %}


{% block content %}
{% if request.user.is_superuser %}

<div class="container mt-5">
	<h2>Create a New Book</h2>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form|crispy }}
		<button type="submit" class="btn btn-primary mt-3">Save Book</button>
	</form>
</div>

{% endif %}
	<!--Container-->
	<div class="container w-full md:w-4/5 xl:w-3/5 mx-auto px-2">

		<!--Title-->
		<h1 class="flex items-center font-sans font-bold break-normal text-indigo-500 px-2 py-8 text-xl md:text-2xl" align='center'>
			The list of the books you can read!
		</h1>

		<!--Card-->
		<div id='recipients' class="p-8 mt-6 lg:mt-0 rounded shadow bg-white">

			<table id="example" class="stripe hover" style="width:100%; padding-top: 1em; padding-bottom: 1em;">
				<thead>
					<tr>
						<th data-priority="1">Title</th>
						<th data-priority="2">Author</th>
						<th data-priority="3">Description</th>
						<th data-priority="4">Publication Year</th>
						<th data-priority="5">Categories</th>
						<th data-priority="6">Availability</th>
                        <th data-priority="7">Count of the copies</th>
						{% if request.user.is_superuser %}
						<th data-priority="8">Update the book</th>
						<th data-priority="9">Delete the book</th>
						{% endif %}
						<th data-priority="10">Book the book : </th>
					</tr>
				</thead>
				<tbody>
                    {% for book in books %}
<tr>
    <td><a href='{% url "books:book_detail" book.pk %}'>{{ book.title }}</a></td>

    <td>{% for author in book.author.all %}
        <a href='{% url "books:author_page" author.pk %}'>{{ author.name|truncatechars:30 }}</a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}</td>

    <td>{{ book.description|truncatechars:30 }}</td>

    <td>{{ book.publication_date|date:"Y" }}</td>

    <td>{% for category in book.category.all %}
        {{ category.title|truncatechars:30 }}
        {% if not forloop.last %}, {% endif %}
    {% endfor %}</td>

    <td>
        {% if book.copy_count > 0 and book.is_available %}
        <span class="text-green-600 font-semibold">Available</span>
        {% else %}
        <span class="text-red-600 font-semibold">Unavailable</span>
        {% endif %}
    </td>
    <td>{{ book.copy_count }}</td>

    {% if request.user.is_superuser %}
    <td><a href='{% url "books:update_book" book.pk %}'>Update</a></td>
    <td><a href='{% url "books:delete_book" book.pk %}'>Delete</a></td>
    <td>
        {% if book.copy_count > 0 and request.user not in book.holders.all %}
        <a href='{% url "books:assign" book.pk %}'>Assign</a>
        {% else %}
        <span class="text-gray-500">Cannot assign</span>
        {% endif %}
    </td>
    {% endif %}
</tr>
{% endfor %}
					
				</tbody>
			</table>

		</div>
		<!--/Card-->

	</div>
	<!--/container-->
	<!-- jQuery -->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

	<!--Datatables -->
	<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
	<script>
		$(document).ready(function() {

			var table = $('#example').DataTable({
				responsive: true
			})
			.columns.adjust()
			.responsive.recalc();
		});
	</script>



<footer style="text-align: center; padding: 10px; background-color: #333; color: #fff; position: fixed; width: 100%; bottom: 0;">
    <p>Текущая дата и время: {{current_time}} </p>
</footer>
{% endblock content %}

librarius/templates/librarius/user_login.html
{% extends "librarius/base.html" %}
{% block content %}
<form method='post' action='{% url "books:login" %}'>
  {% csrf_token %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap items-center">
    <div class="lg:w-3/5 md:w-1/2 md:pr-16 lg:pr-0 pr-0">
      <h1 class="title-font font-medium text-3xl text-gray-900">Your books are always with you</h1>
      <p class="leading-relaxed mt-4">Just rent it here and take it from the library!</p>
    </div>
    <div class="lg:w-2/6 md:w-1/2 bg-gray-100 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
      <h2 class="text-gray-900 text-lg font-medium title-font mb-5">Sign Up</h2>
      <div class="relative mb-4">
        <label for="username" class="leading-7 text-sm text-gray-600">Username</label>
        <input type="text" id="username" name="username" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
      <div class="relative mb-4">
        <label for="password" class="leading-7 text-sm text-gray-600">Password</label>
        <input type="password" id="password" name="password" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
      <button class="text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Log in</button>
      <p class="text-xs text-gray-500 mt-3">Literally you probably haven't heard of them jean shorts.</p>
    </div>
  </div>
</section>
{% endblock content %}